config/routes.rb
Rails.application.routes.draw do

	mathjax 'mathjax'
	root 'static_pages#home'
	get 'home'    => 'static_pages#home'
	get 'main_menu' => 'static_pages#main_menu'
	get 'search_result' => 'questions#search_result'
	get 'user_search_result' => 'users#search_result'
	get 'rate_ranking' => 'rankings#rate_ranking'
	
	resources :questions do
		member do 
			post 'submission' => 'judge_systems#judge'
		end
	end

	devise_for :users do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end

	resources :contests do
		resources :questions do
			member do
				get   'contest_show'
				post 'contest_submission' => 'judge_systems#contest_judge'
			end
		end

		member do
			post 'join'
			get 'sync_ranking'
		end
	end

	resources :users, only:[:show], param: :name do 
		member do
			post 'do_unfollow'
			post 'do_follow'
			get 'follower_list'
			get 'following_list'
			post 'do_unblock'
			post 'do_block'
		end
	end

	#お問い合わせフォーム
	get 'inquiries' => 'inquiries#new'              # 入力画面
	post 'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
	get 'inquiries/thanks' => 'inquiries#thanks'     # 送信完了画面
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
	attr_accessor :i_data, :o_data
	mount_uploader :image, ImageUploader
	belongs_to :created_user, class_name: "User", foreign_key: 'created_user_id'
	has_and_belongs_to_many :users 
	has_many :records, dependent: :destroy
	has_many :posts, dependent: :destroy
	validates :title, presence: true
	validates :content, presence: true
	validates :input, presence: true
	validates :output, presence: true
	validates :question_level, presence: true
	validates :input_text, presence: true
	validates :output_text, presence: true
	validates :sample_input, presence: true
	validates :sample_output, presence: true

	scope :search,							-> (search){ where("title LIKE ?", "%" + search + "%" ).where(for_contest: 0)  }
	scope :include_users,				-> (){ includes(:created_user).includes(:users) }
	scope :for_index_set,				-> (){ select(:id, :created_user_id, :title).includes(:created_user).includes(:users) }
	scope :select_contest_set,	-> (){  }
	scope :level_questoins,			-> (level){ where(question_level: (level - 0.5)...(level + 0.5 )) }
	scope :for_public,					-> (){ where( for_contest: 0 ) }
	scope :for_contest,					-> (){ where( for_contest: 1 ) }

	
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :set_question, only: [:show, :edit, :update, :destroy, :submission,:download_input, :contest_show]
	before_action :set_contest, only: [:contest_show]
	before_action :set_records, only: [:show, :contest_show]
	before_action :authenticate_user!
	# GET /questions
	# GET /questions.json

	def search_result
		@questions = Question.search(params[:search]).for_index_set.page(params[:page]).per(10).order(:id)
	end

	def index
		@level1_questions = Question.for_public.level_questoins(1).for_index_set.page(params[:level1_page]).per(8).order(:id)
		@level2_questions = Question.for_public.level_questoins(2).for_index_set.page(params[:level2_page]).per(8).order(:id)
		@level3_questions = Question.for_public.level_questoins(3).for_index_set.page(params[:level3_page]).per(8).order(:id)
		@level4_questions = Question.for_public.level_questoins(4).for_index_set.page(params[:level4_page]).per(8).order(:id)
		@level5_questions = Question.for_public.level_questoins(5).for_index_set.page(params[:level5_page]).per(8).order(:id)
		@for_contest_questions = current_user.create_questions.for_contest.for_index_set.page(params[:for_contest_page]).per(8).order(:id)
		respond_to do |format|
			format.html
			format.js
		end
	end

	# GET /questions/1
	# GET /questions/1.json
	def show
		not_found	unless for_public?
	end

	def contest_show
		if @contest.users.include?(current_user)
			time_up @contest
		else
			not_found
		end
	end

	# GET /questions/new
	def new
		@question = Question.new
	end

	# GET /questions/1/edit
	def edit
		not_found	if current_user != @question.created_user
	end

	# POST /questions
	# POST /questions.json
	def create
		@question = current_user.create_questions.build(question_params)
		@question.input = StringIO.new(params[:question][:i_data].read).read.gsub(/\R/, "\n")  if params[:question][:i_data]
		@question.output = StringIO.new(params[:question][:o_data].read).read.gsub(/\R/, "\n")  if params[:question][:o_data]
		@question.origin_level =  params[:question][:question_level].to_i
		if @question.save
			post = current_user.posts.build(category: 0)
			@question.posts << post
			current_user.save
			num =  current_user.created_question_number + 1
			current_user.update_attribute(:created_question_number, num)
			redirect_to @question, flash: { notice: 'Question was successfully created.' }
		else
			render :new
		end
	end

	# PATCH/PUT /questions/1
	# PATCH/PUT /questions/1.json
	def update
		@question.input = StringIO.new(params[:question][:i_data].read).read.gsub(/\R/, "\n") if params[:question][:i_data]
		@question.output = StringIO.new(params[:question][:o_data].read).read.gsub(/\R/, "\n") if params[:question][:o_data]

		if @question.update(question_params)
			redirect_to @question, flash: {notice: 'Question was successfully updated.' }
		else
			render :edit 
		end
	end


	# DELETE /questions/1
	def destroy
		@question.destroy
		num =  current_user.created_question_number - 1
		current_user.update_attribute(:created_question_number, num)
		redirect_to questions_path, flash: {notice: 'Question was successfully destroyed.' }
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_question
			@question = Question.find(params[:id])
		end

		def set_contest
			@contest = Contest.find(params[:contest_id])
		end

		def set_records
			@records = current_user.records.where(question_id: @question.id).limit(20).order(created_at: :desc)
		end

		def for_public?
			@question.for_contest == 0 || current_user == @question.created_user && @question.for_contest == 1
		end


		# Never trust parameters from the scary internet, only allow the white list through.
		def question_params
			params.require(:question).permit(:title, :content,:question_id, :input, :output, :i_data, 
				:o_data, :question_level, :input_text, :output_text, :sample_input, :sample_output, :image, :for_contest)
		end
	end

app/helpers/questions_helper.rb
module QuestionsHelper
  
end

app/views/questions/_form.html.erb
<%= form_for @question, html: { class: "form-horizontal question" } do |f| %>

<% if @question.errors.any? %>
<div id="error_expl" class="panel panel-danger">
	<div class="panel-heading">
		<h3 class="panel-title"><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h3>
	</div>
	<div class="panel-body">
		<ul>
			<% @question.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
</div>
<% end %>
<p>記号は$$の間に書き込んでください <%= link_to "記号一覧はこちら","http://www1.kiy.jp/~yoka/LaTeX/latex.html", target: ["_blank"] %></p>

<div class="form-group">
	<%= f.label "image(not must)", class: 'control-label col-xs-12 col-sm-12 col-lg-2' %>
	<div class="col-lg-10">
		<%= f.file_field :image, class: 'form-control' %>
	</div>
</div>
<%= f.hidden_field :image_cache %>

<div class="form-group">
	<%= f.label "title", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<%=f.error_span(:title) %>
</div>

<div class="form-group">
	<%= f.label "Problem Statement", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.text_area :content, class: 'form-control', size: '60x10' %>
	</div>
	<%=f.error_span(:content) %>
</div>

<div class="form-group">
	<%= f.label "Input Format", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.text_area :input_text, class: 'form-control', size: '60x10' %>
	</div>
	<%=f.error_span(:input_text) %>
</div>

<div class="form-group">
	<%= f.label "Output Format", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.text_area :output_text, class: 'form-control', size: '60x10' %>
	</div>
	<%=f.error_span(:output_text) %>
</div>

<div class="form-group">
	<%= f.label "Sample Input", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.text_area :sample_input, class: 'form-control', size: '60x10' %>
	</div>
	<%=f.error_span(:sample_input) %>
</div>

<div class="form-group">
	<%= f.label "Sample Output", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.text_area :sample_output, class: 'form-control', size: '60x10' %>
	</div>
	<%=f.error_span(:sample_output) %>
</div>

<div class="form-group">
	<%= f.label "Input File", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.file_field :i_data, class: 'form-control' %>
	</div>
	<%=f.error_span(:i_data) %>
</div>

<div class="form-group">
	<%= f.label "Output File", class: 'control-label col-lg-2' %>
	<div class="col-lg-10">
		<%= f.file_field :o_data, class: 'form-control' %>
	</div>
	<%=f.error_span(:o_data) %>
</div>

<% if @path.is('questions#new') || @path.is('questions#create') %>
<div class="form-group">
	<%= f.label "Problem Level", class: 'control-label col-lg-2' %>
	<div class="btn-group" data-toggle="buttons">
		<label class="btn btn-warning active">
			<%= f.radio_button :question_level, 1, autocomplete: "off", checked: true %>1
		</label>
		<label class="btn btn-warning">
			<%= f.radio_button :question_level, 2, autocomplete: "off" %>2
		</label>
		<label class="btn btn-warning">
			<%= f.radio_button :question_level, 3, autocomplete: "off" %>3
		</label>
		<label class="btn btn-warning">
			<%= f.radio_button :question_level, 4, autocomplete: "off" %>4
		</label>
		<label class="btn btn-warning">
			<%= f.radio_button :question_level, 5, autocomplete: "off" %>5
		</label>
	</div>
	<%=f.error_span(:question_level) %>
</div>
<div class="form-group">
	<%= f.label "For Contest?", class: 'control-label col-lg-2' %>
	<%= f.radio_button :for_contest, 1 %> yes
	<%= f.radio_button :for_contest, 0,  checked: true %> no
</div>
<% end %>
<div class="form-group">
	<div class="col-lg-offset-2 col-lg-10" style="margin-bottom: 30px">
		<%= f.submit "Create Problem", class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/questions/_list.html.erb
<table class="table table-borderd">
	<thead>
		<tr>
			<th>number</th>
			<th>title</th>
			<th> created </th>
			<th>accepted </th>
			<th>condition</th>
		</tr>
	</thead>
	<tbody>
		
		<% questions.each do |question| %>
			<% if @path.is("contests#show") %>
			<% if @contest.end? %>
			<% path = contest_question_path(@contest, question) %>
			<% else %>
			<% path = contest_show_contest_question_path(@contest, question) %>
			<% end %>
			<% else %>
			<% path = question_path(question) %>
			<% end %>
		<tr>
			<td><%=  question.id %></td>
			<td><%= link_to question.title, path %></td>
			
			<td><%= link_to question.created_user.name, question.created_user  %></td>
			<td><%= question.users.length %></td>
			<% if question.created_user == current_user %>
			<td style="color: blue;"><strong>you create</strong></td>
			<% elsif current_user.questions.include?(question) %>
			<td style="color: green;" ><strong>AC</strong></td>
			<% elsif current_user.records.find_by(question_id: question.id) %>
			<td style="color: red;" ><strong>WA</strong></td>
			<% else %>
			<td style="color: gray;" ><strong>---------</strong></td>
			<% end %>
		</tr>
		
		<% end %>
	</tbody>
</table>  

app/views/questions/_question_body.html.erb
<% if @path.is("questions#contest_show") %>
<%= link_to "Back", contest_path(@contest), class: 'btn btn-default btn-lg' %>
<% else %>
<%= link_to "Back", :back, class: 'btn btn-default btn-lg' %>
<% end %>
<div class="row">
	<div class="col-sm-12  col-md-10 col-md-offset-1">

		<ul class="nav nav-tabs" role="tablist">
			<li class="active" role="presentation">
				<a aria-controls="tab_1" data-toggle="tab" href="#tab_1" role="tab" class="table-list">question</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_2" data-toggle="tab" href="#tab_2" role="tab" class="table-list">submit</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_3" data-toggle="tab" href="#tab_3" role="tab" class="table-list">records</a>
			</li>
		</ul>

		<div class="tab-content">
			<div class="tab-pane fade in active" id="tab_1" role="tabpanel">
				<%= render partial: 'question_content' %>
			</div>
			<div class="tab-pane fade" id="tab_2" role="tabpanel">
				<%= render 'judge_systems/form', submit_path: path %>
			</div>
			<div class="tab-pane fade" id="tab_3" role="tabpanel">
				<%= render 'record_list' %>
			</div>
		</div>

	</div>
</div>

app/views/questions/_question_content.html.erb
<dl>
	<dt><strong><h4>title:<%= @question.title %></h4></strong></dt>
	<dt>level: <%= @question.question_level.round %></dt>
	<%= image_tag @question.image_url , size: "400x300", style: "margin-bottom: 20px;" if @question.image? %>
	<dt>Question Statement</dt>
	<dd><%== markdown(@question.content) %></dd>
	<dt>Input</dt>
	<dd><%== markdown(@question.input_text) %></dd>
	<dt>Ouput</dt>
	<dd><%== markdown(@question.output_text) %></dd>
	<dt>Sample Input</dt>
	<dd><%== markdown(@question.sample_input) %></dd>
	<dt>Sample Output</dt>
	<dd><%== markdown(@question.sample_output) %></dd>
</dl>
<script>
	MathJax.Hub.Typeset();
</script>

<% if current_user == @question.created_user %>
<%= link_to "Edit",edit_question_path(@question), class: 'btn btn-default btn-lg' %>
<%= link_to "Delete",
question_path(@question),
method: 'delete',
data: { confirm:  "一度削除した問題のデータは復元できません。\n本当に削除しますか？" },
class: 'btn btn-danger btn-lg' %>
<% end %>

app/views/questions/_question_space.html.erb
<dl class="col-xs-12 col-sm-12 col-md-offset-1 col-md-7">
	<dt><strong><h4>title:<%= @question.title %></h4></strong></dt>
	<dt>level: <%= @question.question_level.round %></dt>
	<%= image_tag @question.image_url , size: "400x300", style: "margin-bottom: 20px;" if @question.image? %>
	<dt>Question Statement</dt>
	<dd><%== markdown(@question.content) %></dd>
	<dt>Input</dt>
	<dd><%== markdown(@question.input_text) %></dd>
	<dt>Ouput</dt>
	<dd><%== markdown(@question.output_text) %></dd>
	<dt>Sample Input</dt>
	<dd><%== markdown(@question.sample_input) %></dd>
	<dt>Sample Output</dt>
	<dd><%= markdown(@question.sample_output).html_safe %></dd>
	<dd><%= link_to 'input download', download_input_question_path(@question),class: "btn btn-default" %></dd>
	<% if @path.is('questions#show') %>
	<dd><%= link_to('submission', {controller: 'judge_systems', action: action, question_id: @question.id}, class: "btn btn-primary", style: "color: white") %></dd>
	<% else %>
	<dd><%= link_to('submission', {controller: 'judge_systems', action: action, question_id: @question.id, contest_id: @contest.id }, class: "btn btn-primary", style: "color: white") %></dd>
	<% end %>
</dl>
<script>
	MathJax.Hub.Typeset();
</script>

app/views/questions/_record_list.html.erb
<div class="col-xs-12 col-md-6 col-md-offset-3">
<h2 class="text-center">This problems Log</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th><%= :submitted_at%></th>
			<th><%= :result %></th>
		</tr>
	</thead>
	<tbody class="update_record">
		<% @records.each do |record| %>
		<tr>
			<td><%= record.created_at %></td>
			<td><%= record.result %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/questions/contest_show.html.erb
<%= render 'question_body', path: contest_submission_contest_question_path(@contest, @question) %>

app/views/questions/edit.html.erb
<% provide(:title, "Edit Question") %>
<div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
	<%= render partial: 'form' %>
</div>

app/views/questions/index.html.erb
<div class="row">
	<div class="col-xs-12 col-md-4 col-md-offset-8">
		<%= form_tag search_result_path, method: 'get' do %><%#　projects_pathはモデル名で読みかえること %>
		<div class="form-group">
			<%= text_field_tag :search, params[:search], placeholder: "Question name"  %>                 
			<%= submit_tag "Search", title: nil, class: 'btn btn-primary' %>
		</div>
		<% end %>
	</div>
</div>
<h2 class="text-center">Question List</h2>

<div class="row">
	<div class="col-sm-12  col-md-10 col-md-offset-1">
		<ul class="nav nav-tabs" role="tablist">
			<li class="active" role="presentation">
				<a aria-controls="tab_1" data-toggle="tab" href="#tab_1" role="tab" class="table-list">level 1</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_2" data-toggle="tab" href="#tab_2" role="tab" class="table-list">level 2</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_3" data-toggle="tab" href="#tab_3" role="tab" class="table-list">level 3</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_4" data-toggle="tab" href="#tab_4" role="tab" class="table-list">level 4</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_5" data-toggle="tab" href="#tab_5" role="tab" class="table-list">level 5</a>
			</li>
			<li role="presentation">
				<a aria-controls="tab_6" data-toggle="tab" href="#tab_6" role="tab" class="table-list">for contest</a>
			</li>
		</ul>

		<div class="tab-content">
			<div class="tab-pane fade in active" id="tab_1" role="tabpanel">
				<%= render partial: 'list', locals: { questions: @level1_questions } %>
				<%= paginate @level1_questions, param_name: :level1_page , remote: true %>
			</div>
			<div class="tab-pane fade" id="tab_2" role="tabpanel">
				<%= render partial: 'list', locals: { questions: @level2_questions } %>
				<%= paginate @level2_questions, param_name: :level2_page , remote: true %>
			</div>

			<div class="tab-pane fade" id="tab_3" role="tabpanel">
				<%= render partial: 'list', locals: { questions: @level3_questions } %>
				<%= paginate @level3_questions, param_name: :level3_page , remote: true %>
			</div>

			<div class="tab-pane fade" id="tab_4" role="tabpanel">
				<%= render partial: 'list', locals: { questions: @level4_questions } %>
				<%= paginate @level4_questions, param_name: :level4_page , remote: true %>
			</div>

			<div class="tab-pane fade" id="tab_5" role="tabpanel">
				<%= render partial: 'list', locals: { questions: @level5_questions } %>
				<%= paginate @level5_questions , param_name: :level5_page , remote: true %>
			</div>

				<div class="tab-pane fade" id="tab_6" role="tabpanel">
				<%= render partial: 'list', locals: { questions: @for_contest_questions } %>
				<%= paginate @for_contest_questions, param_name: :for_contest_page , remote: true %>
			</div>

		</div>
	</div>
</div>

app/views/questions/index.js.erb
$("#tab_1").html("<%= j(render partial: 'list', locals: { questions: @level1_questions, level_page: :level1_page }) %>");
$("#tab_2").html("<%= j(render partial: 'list', locals: { questions: @level2_questions, level_page: :level2_page }) %>");
$("#tab_3").html("<%= j(render partial: 'list', locals: { questions: @level3_questions, level_page: :level3_page }) %>");
$("#tab_4").html("<%= j(render partial: 'list', locals: { questions: @level4_questions, level_page: :level4_page }) %>");
$("#tab_5").html("<%= j(render partial: 'list', locals: { questions: @level5_questions, level_page: :level5_page }) %>");

app/views/questions/new.html.erb
<div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
	<%= render partial: 'form' %>
</div>

app/views/questions/search_result.html.erb
<h2 class="text-center">Search Result</h2>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
		<%= render partial: 'list', locals: { questions: @questions, level_page: :page} %>
	</div>
</div>
<div class="row">
	<div class="col-md-10 col-md-offset-1"> 
		<%= link_to "Back", questions_path, class: "btn btn-default" %>
	</div>
</div>

app/views/questions/show.html.erb
<%= render 'question_body', path: submission_question_path(@question) %>