config/routes.rb
Rails.application.routes.draw do

	mathjax 'mathjax'
	root 'static_pages#home'
	get 'home'    => 'static_pages#home'
	get 'main_menu' => 'static_pages#main_menu'
	get 'search_result' => 'questions#search_result'
	get 'user_search_result' => 'users#search_result'
	get 'rate_ranking' => 'rankings#rate_ranking'
	
	resources :questions do
		member do 
			post 'submission' => 'judge_systems#judge'
		end
	end

	devise_for :users do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end

	resources :contests do
		resources :questions do
			member do
				get   'contest_show'
				post 'contest_submission' => 'judge_systems#contest_judge'
			end
		end

		member do
			post 'join'
			get 'sync_ranking'
		end
	end

	resources :users, only:[:show], param: :name do 
		member do
			post 'do_unfollow'
			post 'do_follow'
			get 'follower_list'
			get 'following_list'
			post 'do_unblock'
			post 'do_block'
		end
	end

	#お問い合わせフォーム
	get 'inquiries' => 'inquiries#new'              # 入力画面
	post 'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
	get 'inquiries/thanks' => 'inquiries#thanks'     # 送信完了画面
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


	def home
		redirect_to :main_menu if user_signed_in?
	end

	def main_menu
		authenticate_user!
		@posts = Post.follows_post(current_user).includes(:question).includes(:contest).includes(:user).order(created_at: :desc).page(params[:page]).per(10)
		@created_users = User.all.select(:name, :created_question_number, :rate).limit(5).order(created_question_number: :desc)
		@solved_users = User.all.select(:name, :solved_question_number, :rate).limit(5).order(solved_question_number: :desc)
		@rate_users = User.all.select(:name, :rate).limit(5).order(rate: :desc)
		@recent_contests = current_user.contests.future_contests.select(:id,:title, :start_time).order(start_time: :desc)
		@now_contests = current_user.contests.now_contests.select(:id, :title, :start_time).limit(10).order(start_time: :desc)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def link_to_next_page(scope, name, options = {}, &block)
		param_name = options.delete(:param_name) || Kaminari.config.param_name
		link_to_unless scope.last_page?, name, {param_name => (scope.current_page + 1)}, options.merge(:rel => 'next') do
			block.call if block
		end
	end
end

app/views/static_pages/_auto_slide.html.erb
<div id="test-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">

	<!-- 何枚目かの画像かを表すインディケーター -->
	<ol class="carousel-indicators">
		<!--li data-target="#test-carousel" data-slide-to="0" class="active"></li>-->
		<!--<li data-target="#test-carousel" data-slide-to="1" class=""></li>-->
	</ol>

	<!-- 実際の画像の表示処理 -->
	<div class="carousel-inner">
		<div class="item active">    <!-- activeをつけたものがページ表示時に表示される -->
			<%= image_tag asset_path("main_menu/1.jpg"), size: "300x300", class: "center-block img-responsive" %>
		</div>
		<%# 2.upto 3 do |i| %>
		<!--div class="item"-->
			<%# image_tag asset_path("main_menu/1.jpeg"), class: "center-block", size: "300x300" %>
		<!--</div>-->
		<%# end %>
	</div>

	<!-- 前の画像へ戻るための矢印ポインタ -->
	<a class="left carousel-control" href="#test-carousel" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left"></span>
	</a>

	<!-- 次の画像へ進むための矢印ポインタ -->
	<a class="right carousel-control" href="#test-carousel" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right"></span>
	</a>
</div>

app/views/static_pages/_contest_list.html.erb
 <table class="table table-borderd"> 
	<tbody>
		<% @recent_contests.each do |contest| %>
		<tr>
			<td>
				<%= contest.start_time %>
				<br>
		
				<br>
				<%= link_to "title: #{contest.title}", contest %>
		</tr>
		<% end %>
	</tbody>
 </table>

app/views/static_pages/_create_ranking_list.html.erb
<h2 class="text-center">Best Creaters Ranking</h2>
<table class="table table-borderd">
	<tbody>
		<% number = 1 %>
		<% @created_users.each do |user| %>
		<tr class="text-center">
			<td><%= number %></td>
			<td><%= link_to user.name, user, style: "color:#{rate_color user.rate}"  %></td>
			<td><%= user.created_question_number.to_s + "問" %></td>
		</tr>
		<% number += 1 %>
		<% if number == 6 %>
		<% break %>
		<% end %>
		<% end %>
	</tbody>
</table> 

app/views/static_pages/_now_contest.html.erb
 <table class="table table-borderd"> 
	<tbody>
		<% @now_contests.each do |contest| %>
		<tr>
			<td>
				<%= contest.start_time %>
				<br>
		
				<br>
				<%= link_to "title: #{contest.title}", contest %>
		</tr>
		<% end %>
	</tbody>
 </table>

app/views/static_pages/_ranking_list.html.erb
<h2 class="text-center"><%= title %></h2>
<table class="table table-striped">
  <tbody>
  <% number = 1 %>
    <% users.each do |user| %>
    <tr class="text-center">
    <td><%= number %></td>
      <td><%= link_to user.name, user, style: "color:green;"  %></td>
    </tr>
    <% number += 1 %>
    <% if number == 6 %>
    <% break %>
    <% end %>
    <% end %>
  </tbody>
</table> 

app/views/static_pages/_rate_ranking_list.html.erb
<h2 class="text-center">Best Rate Ranking</h2>
<table class="table table-borderd">
	<tbody>
		<% number = 1 %>
		<% @rate_users.each do |user| %>
		<tr class="text-center">
			<td><%= number %></td>
			<td><%= link_to user.name, user, style: "color:#{rate_color user.rate}" %></td>
			<td style="color:<%= rate_color user.rate %>"><%= user.rate %></td>
		</tr>
		<% number += 1 %>
		<% if number == 6 %>
		<% break %>
		<% end %>
		<% end %>
	</tbody>
</table> 

app/views/static_pages/_solve_ranking_list.html.erb
<h2 class="text-center">Best Answerers Ranking</h2>
<table class="table table-borderd">
	<tbody>
		<% number = 1 %>
		<% @solved_users.each do |user| %>
		<tr class="text-center">
			<td><%= number %></td>
			<td><%= link_to user.name, user, style: "color:#{rate_color user.rate}"  %></td>
			<td><%= user.solved_question_number.to_s + "問"%></td>
		</tr>
		<% number += 1 %>
		<% if number == 6 %>
		<% break %>
		<% end %>
		<% end %>
	</tbody>
</table> 

app/views/static_pages/_time_line.html.erb
 <table class="table table-borderd" id="lists"> 
 	<tbody>
 		<% @posts.each do |post| %>
 		<% if (current_user.following.include?(post.user) || current_user == post.user)   %>
 		<% if (post.category == 0 || post.category == 1) && post.question.for_contest == 0 %>
 		<tr>
 			<td>
 				<%= date_format post.created_at %>
 				<br>
 				<%="#{post.user.name}さんが"%>
 				<br>
 				<%= link_to "問題:#{post.question.title}", post.question %>
 				<br>
 				<% if post.category == 0 %>
 				<%="を作成しました" %>
 				<% else %>
 				<%="でAcceptされました" %>
 				<% end %>
 			</td>
 		</tr>
 		<% elsif post.category == 2 ||  post.category == 3 %>
 		<tr>
 			<td>
 				<%= date_format post.created_at %>
 				<br>
 				<%="#{post.user.name}さんが"%>
 				<br>
 				<%= link_to "コンテスト:#{post.contest.title}", post.contest %>
 				<br>
 				<% if post.category == 2 %>
 				<%="に参加をしました" %>
 				<% else %>
 				<%="を作成しました" %>
 				<% end %>
 			</td>
 		</tr>
 		<% end %>
 		<% end %>
 		<% end %>
 	</tbody>
 </table>

app/views/static_pages/_update_info.html.erb
<table class="table table-bordered " id="lists"> 
	<tbody>
		<tr>
			<td>
				12/25 レイアウトを修正しました <br>
				スマホ、タブレットに対応しました！ <br>
			</td>
		</tr>
		<tr>
			<td>
				12/23 レイアウトを修正しました <br>
				ランキングをつけました <br>
			</td>
		</tr>
		<tr>
			<td>
				12/21 レイアウトを修正しました <br>
				アイコンをつけました <br>
				ブロック機能をつけました
			</td>
		</tr>
		<tr>
			<td>
				12/20 レイアウトを修正しました <br>
				Latexの使い方のリンクを更新しました
			</td>
		</tr>
		<tr>
			<td>
				12/19 Question Listでアクセプト状況を確認できるようになりました <br>
				メインメニューのレイアウトを向上させました。自動スクロールを実装しました <br>
				ユーザーページのレイアウトを向上させました
			</td>
		</tr>
		<tr>
			<td>
				12/18 Update Infoを作りました。レイアウトをいい感じにしました
			</td>
		</tr>
	</tbody>
</table>

app/views/static_pages/home.html.erb
<%= image_tag asset_path("home/top.jpg"), size: "600x700", class: "center-block img-responsive" %>
<div class="jumbotron text-center">

	<h1>Welcome to DCOJ</h1>
	<p>Here is Daisuki Club Online Judge. You can practice competition programming and compete with rivals of the world!</p>
	<div style="text-align:center; padding-top: 60px;">
		<%= link_to "Let's start now!", new_user_registration_path, class: 'btn btn-primary btn-xxl',style: "color: white;"%>
	</div>

</div>

app/views/static_pages/main_menu.html.erb
<div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12" style=" border: 1px solid #c0c0c0; ">
		<%= render partial: 'auto_slide' %>
	</div>
</div>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="col-xs-12 col-sm-12 col-md-4">
			<div style="border: 1px solid #c0c0c0; background-color: white; margin-top:80px; ">
				<h2 class="text-center" >Time Line</h2>
				<div style="height:300px; overflow-y:scroll; -webkit-overflow-scrolling: touch;">
					<%= render partial: 'time_line' %>
					<%= link_to_next_page( @posts, 'more', remote: true, id: 'view_more1', class: "btn btn-info col-xs-12 col-sm-12 col-md-12") %>
				</div>  
			</div>
		</div>

		<div class="col-xs-12 col-sm-12 col-md-4">
			<div style="border: 1px solid #c0c0c0; background-color: white; margin-top:80px;">
				<h2 class="text-center" >Now Contests</h2>
				<div style="height:300px; overflow-y:scroll; -webkit-overflow-scrolling: touch;">
					<%= render partial: 'now_contest' %>
				</div>
			</div>
		</div>

		<div class="col-xs-12 col-sm-12 col-md-4">
			<div style="border: 1px solid #c0c0c0; background-color: white; margin-top:80px;">
				<h2 class="text-center" >Comming Up Contests</h2>
				<div style="height:300px; overflow-y:scroll; -webkit-overflow-scrolling: touch;">
					<%= render partial: 'contest_list' %>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row" style="margin-top: 80px;">
	<div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
		<%= render partial: 'rate_ranking_list' %>
		<strong><%= link_to 'more ranking', rate_ranking_path %></strong>
	</div>
</div>
<div class="row" style="margin-top: 80px;">
	<div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
		<%= render partial: 'create_ranking_list' %>
	</div>
</div>
<div class="row" style="margin-top: 80px; margin-bottom: 80px;">
	<div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
		<%= render partial: 'solve_ranking_list' %>
	</div>
</div>
</div>

app/views/static_pages/main_menu.js.erb
$('#lists').append("<%= escape_javascript(render partial: 'time_line', object: @posts) %>");
$("#view_more1").replaceWith("<%= escape_javascript(link_to_next_page( @posts, 'more', remote: true, id: 'view_more1', class: "btn btn-info col-xs-12 col-sm-12 col-md-12")) %>");