config/routes.rb
Rails.application.routes.draw do

	mathjax 'mathjax'
	root 'static_pages#home'
	get 'home'    => 'static_pages#home'
	get 'main_menu' => 'static_pages#main_menu'
	get 'search_result' => 'questions#search_result'
	get 'user_search_result' => 'users#search_result'
	get 'rate_ranking' => 'rankings#rate_ranking'
	
	resources :questions do
		member do 
			post 'submission' => 'judge_systems#judge'
		end
	end

	devise_for :users do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end

	resources :contests do
		resources :questions do
			member do
				get   'contest_show'
				post 'contest_submission' => 'judge_systems#contest_judge'
			end
		end

		member do
			post 'join'
			get 'sync_ranking'
		end
	end

	resources :users, only:[:show], param: :name do 
		member do
			post 'do_unfollow'
			post 'do_follow'
			get 'follower_list'
			get 'following_list'
			post 'do_unblock'
			post 'do_block'
		end
	end

	#お問い合わせフォーム
	get 'inquiries' => 'inquiries#new'              # 入力画面
	post 'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
	get 'inquiries/thanks' => 'inquiries#thanks'     # 送信完了画面
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	include Resonatable
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable,
	:recoverable, :lockable, :timeoutable, :authentication_keys => [:login]

	attr_accessor :login
	mount_uploader :image, ImageUploader
	has_many :create_questions, class_name: "Question", foreign_key: 'created_user_id', dependent: :destroy
	has_and_belongs_to_many :questions
	has_many :records, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :create_contests, class_name: "Contest", foreign_key: 'created_user_id', dependent: :destroy
	has_many :joins
	has_many :contests, through: :joins
	validates :account, presence: true, uniqueness: { case_sensitive: false }
	validates :name, presence: true

	scope :search, -> (search){ where("name LIKE ? ", "%" + search + "%" ) }


	def to_param
		name
	end


	def self.find_first_by_auth_conditions(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions).where(["account = :value OR lower(email) = lower(:value)", { :value => login }]).first
		else
			where(conditions).first
		end
	end

	def self.update_rate_rank
		users = User.select(:id, :rate).all.order(rate: :desc)
		rank = 0
		number = 1
		users.size.times do |key|
			if key == 0
				rank += number
			elsif key > 0
				if users[key].rate == users[key - 1].rate
					number += 1
				else
					rank += number
					number = 1
				end
			end
			users[key].update_columns(rate_rank: rank)
		end
	end


	private

	def validate_password?
		password.present? || password_confirmation.present?
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :follower_list, :following_list]
	before_action :authenticate_user!
	# GET /users/1
	# GET /users/1.json
	def show
		not_found if @user.blocking?(current_user)
		@records = @user.records.order(created_at: :desc).page(params[:records_page]).per(5)
		@create_questions = @user.create_questions.for_public.includes(:created_user).includes(:users).select(:id, :title, :created_user_id, :question_level).order(:id).page(params[:create_questions_page]).per(5)
		@solve_questions = @user.questions.for_public.includes(:created_user).includes(:users).select(:id, :title, :created_user_id, :question_level).order(:id).page(params[:solve_questions_page]).per(5)
		respond_to do |format|
			format.html
			format.js
		end
	end

	def do_follow
		@user = User.find_by(account: params[:follow_account])
		current_user.follow @user 
		redirect_to @user
	end

	def do_unfollow
		@user = User.find_by(account: params[:follow_account])
		current_user.unfollow @user
		redirect_to @user
	end

	def do_block
		@user = User.find_by(account: params[:block_account])
		current_user.block @user 
		redirect_to @user
	end

	def do_unblock
		@user = User.find_by(account: params[:block_account])
		current_user.unblock @user
		redirect_to @user
	end

	def follower_list
		@users = @user.followers.select(:id,:name, :image).order(:id).page(params[:page]).per(12)
	end

	def following_list
		@users = @user.following.select(:id, :name, :image).order(:id).page(params[:page]).per(12)
	end

	def search_result
		@users = User.search(params[:search]).select(:id, :name, :image).page(params[:page]).per(12)
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_user
			@user = User.find_by(name: params[:name])
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_block.html.erb
<%= form_for :user, url: do_block_user_path(@user), remote: true do |f| %>
<div><%= hidden_field_tag :block_account, @user.account %></div>
  <%= f.submit "Block", class: "btn btn-danger btn-lg col-xs-6 col-sm-6 col-md-1" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for :user, url: do_follow_user_path(@user), remote: true do |f| %>
<div><%= hidden_field_tag :follow_account, @user.account %></div>
<%= f.submit "Follow", class: "btn btn-primary btn-lg col-xs-6 col-sm-6 col-md-1 col-md-offset-2" %>
<% end %>

app/views/users/_log_list.html.erb
<table class="table table-borderd">
	<thead>
		<tr>
			<th><%= :title%></th>
			<th><%= :submitted_at%></th>
			<th><%= :result %></th>
		</tr>
	</thead>

	<tbody>
		<% @records.each do |record| %>
		<% next unless record.question.for_contest == 0 %>
		<tr>
			<td><%=link_to record.question.title, record.question %></td>
			<td><%= record.created_at %></td>
			<td><%= record.result %></td>
		</tr>
		<% end %>
	</tbody>
</table> 
<%= paginate @records , param_name: :records_page, remote: true %>

app/views/users/_question_list.html.erb
<table class="table table-borderd">
	<thead>
		<tr>
			<th><%= :number %></th>
			<th><%= :title %></th>
			<th><%= :created %></th>
			<th><%= :accepted %></th>
			<th>level</th>
		</tr>
	</thead>
	<tbody>
		<% questions.each do |question| %>
		<tr>
			<td><%=  question.id %></td>
			<td><%= link_to question.title, question %></td>
			<td><%= link_to question.created_user.name,question.created_user %></td>
			<td><%= question.users.length %></td>
			<td><%= question.question_level.to_i %></td>
		</tr>
		<% end %>
	</tbody>
</table>  
<%= paginate questions, param_name: level_page, remote: true %>

app/views/users/_unblock.html.erb
<%= form_for :user, url: do_unblock_user_path(@user), remote: true do |f| %>
<div><%= hidden_field_tag :block_account, @user.account %></div>
  <%= f.submit "Unblock", class: "btn btn-default btn-lg col-xs-6 col-sm-6 col-md-1" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for :user, url: do_unfollow_user_path(@user), remote: true do |f| %>
<div><%= hidden_field_tag :follow_account, @user.account %></div>
<%= f.submit "Unfollow", class: "btn btn-default btn-lg col-xs-6 col-sm-6 col-md-1 col-md-offset-2" %>
<% end %>

app/views/users/_user_list.html.erb
<div class="lists">
	<% @users.each do |user| %>
	<div class="col-xs-4 col-sm-4 col-md-4">
		<%= link_to image_tag(user_icon(user), class: "img-circle img-responsive", size: '250x250'), user %>
		<div class="center-block">
			<h3><strong><%= user.name %></strong></h3>
		</div>
	</div>
	<% end %>
</div>

app/views/users/follower_list.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-3 col-md-offset-3">
		<h1> <%= fa_icon "user" %> Follower List</h1>
	</div>
</div>
<div class="row">
	<div class="col-xs-12  col-sm-12 col-md-8 col-md-offset-2">

		<div id="lists">
			<div class="page">
				<%= render partial: 'user_list' %>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12  col-sm-12 col-md-8 col-md-offset-2" style="display: none;">
		<%= paginate @users %>
	</div>
</div>


<%= javascript_include_tag 'jquery.infinitescroll' %>
<script>
	$("#lists .page").infinitescroll({
		loading: {
			img:     "http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_48.gif",
			msgText: "loading..."
		},
		navSelector: "nav.pagination",
		nextSelector: "nav.pagination a[rel=next]",
		itemSelector: "#lists div.lists" /* このDOMに差し掛かった時に、次のページのロードが始まる*/
	});

</script>

app/views/users/follower_list.js.erb
$("#lists").append("<div class='page'><%= escape_javascript( render partial: 'user_list' ) %></div>");

app/views/users/following_list.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-3 col-md-offset-3">
		<h1> <%= fa_icon "user-o" %> Following List</h1>
	</div>
</div>
<div class="row">
	<div class="col-xs-12  col-sm-12 col-md-8 col-md-offset-2">

		<div id="lists">
			<div class="page">
				<%= render partial: 'user_list' %>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12  col-sm-12 col-md-8 col-md-offset-2" style="display: none;">
		<%= paginate @users %>
	</div>
</div>


<%= javascript_include_tag 'jquery.infinitescroll' %>
<script>
	$("#lists .page").infinitescroll({
		loading: {
			img:     "http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_48.gif",
			msgText: "loading..."
		},
		navSelector: "nav.pagination",
		nextSelector: "nav.pagination a[rel=next]",
		itemSelector: "#lists div.lists" /* このDOMに差し掛かった時に、次のページのロードが始まる*/
	});

</script>

app/views/users/following_list.js.erb
$("#lists").append("<div class='page'><%= escape_javascript( render partial: 'user_list' ) %></div>");

app/views/users/search_result.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-3 col-md-offset-3">
		<h2 class="text-center">Search Result</h2>
	</div>
</div>
<div class="row">
	<div class="col-xs-12  col-sm-12 col-md-8 col-md-offset-2">

		<div id="lists">
			<div class="page">
				<%= render partial: 'user_list' %>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12  col-sm-12 col-md-8 col-md-offset-2" style="display: none;">
		<%= paginate @users %>
	</div>
</div>

<%= javascript_include_tag 'jquery.infinitescroll' %>
<script>
	$("#lists .page").infinitescroll({
		loading: {
			img:     "http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_48.gif",
			msgText: "loading..."
		},
		navSelector: "nav.pagination",
		nextSelector: "nav.pagination a[rel=next]",
		itemSelector: "#lists div.lists" /* このDOMに差し掛かった時に、次のページのロードが始まる*/
	});

</script>

app/views/users/show.html.erb
<% provide(:title, "User Profile") %>

<div class="row">

	<%= image_tag user_icon(@user), size: "130x130", class: "img-circle center-block", style: "margin-bottom: 30px;"%>


</div>


<div class="row" style="margin-bottom: 10px;">
	<div class="text-center">
		<h3><strong style="color:<%= rate_color @user.rate %>"><%= @user.name %></strong></h3>
		<dd><strong>rate:</strong><strong style="color:<%= rate_color @user.rate %>"> <%= @user.rate %></strong></dd>
		<dd><strong><%= "account: #{@user.account}" if current_user == @user %></strong></dd>
		<dd><strong><%= "created: #{@user.created_question_number}" %></strong></dd>
		<dd><strong><%= "solved: #{@user.solved_question_number}" %></strong></dd>
	</div>
</div>
<div class="row">

	<% unless current_user == @user %>
	<div class="row">
		<div id="follow_form">
			<% if current_user.following?(@user) %>
			<%= render partial: 'unfollow' %>
			<% else %>
			<%= render partial: 'follow' %>
			<% end %>
		</div>

		<div id="block_form">
			<% if current_user.blocking?(@user) %>
			<%= render partial: 'unblock' %>
			<% else %>
			<%= render partial: 'block' %>
			<% end %>
		</div>
	</div>
	<% else %>
	<%= link_to "Edit", edit_user_registration_path, class: 'btn btn-default btn-lg col-xs-12 col-sm-12 col-md-2 col-md-offset-5' %>
	<% end %>

</div>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-5 col-md-offset-1">
		<h2 class="text-center">Created Questions</h2>
		<div id="create_questions">
			<%= render partial: 'question_list', locals: { questions: @create_questions, level_page:  
			:create_questions_page } %>
		</div>
	</div>

	<div class="col-xs-12 col-sm-12 col-md-5">
		<h2 class="text-center">Solved Questions</h2>
		<div  id="solve_questions">
			<%= render partial: 'question_list', locals: { questions: @solve_questions, level_page:  
			:solve_questions_page } %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
		<h2 class="text-center">Logs</h2>
		<div  id="records">
			<%= render partial: 'log_list' %>
		</div>
	</div>
</div>

app/views/users/show.js.erb
$("#create_questions").html("<%= j(render partial: 'question_list', locals: { questions: @create_questions, level_page: :create_questions_page }) %>");
$("#solve_questions").html("<%= j(render partial: 'question_list', locals: { questions: @solve_questions, level_page: :solve_questions_page }) %>");
$("#records").html("<%= j(render partial: 'log_list') %>");
$("#follow_form").html("<%= j(render partial: 'follow') %>");
$("#follow_form").html("<%= j(render partial: 'unfollow') %>");
$("#block_form").html("<%= j(render partial: 'block') %>");
$("#block_form").html("<%= j(render partial: 'unblock') %>");