config/routes.rb
Rails.application.routes.draw do

	mathjax 'mathjax'
	root 'static_pages#home'
	get 'home'    => 'static_pages#home'
	get 'main_menu' => 'static_pages#main_menu'
	get 'search_result' => 'questions#search_result'
	get 'user_search_result' => 'users#search_result'
	get 'rate_ranking' => 'rankings#rate_ranking'
	
	resources :questions do
		member do 
			post 'submission' => 'judge_systems#judge'
		end
	end

	devise_for :users do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end

	resources :contests do
		resources :questions do
			member do
				get   'contest_show'
				post 'contest_submission' => 'judge_systems#contest_judge'
			end
		end

		member do
			post 'join'
			get 'sync_ranking'
		end
	end

	resources :users, only:[:show], param: :name do 
		member do
			post 'do_unfollow'
			post 'do_follow'
			get 'follower_list'
			get 'following_list'
			post 'do_unblock'
			post 'do_block'
		end
	end

	#お問い合わせフォーム
	get 'inquiries' => 'inquiries#new'              # 入力画面
	post 'inquiries/confirm' => 'inquiries#confirm'   # 確認画面
	get 'inquiries/thanks' => 'inquiries#thanks'     # 送信完了画面
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
		
			<% flash.each do |name, msg| %>
			<% next if name == 'timedout' %>
			<div class='alert alert-<%= name == "notice" ? "success" : "danger" %>'>
				<a class="close" data-dismiss="alert">×</a> <!-- アラートダイアログに×ボタンをつける -->
				<%= msg %>
				<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer :q">
	<div class="container-fluid">
		<div row>
			<p class="text-muted col-xs-12 col-sm-12 col-md-12">&copy;Copyright Programming Daisuki Club. All rights reserved.
				<%= link_to "お問い合わせ", inquiries_path, class: "btn btn-default" %></p>
			</div>
		</div>
	</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top" style="background-color: #00ada9;">
	<div class="container-fluid">
		<%= link_to image_tag(asset_path("layout/pdc-logo.png"), size: "53x47", class: "img-circle"), home_path, class: " navbar-nav" %>
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-nav">
			<%= fa_icon("list") + " Manu" %>
		</button>
		<% if user_signed_in? %>
		<div class="collapse navbar-collapse" id="top-nav">
			<div class="nav navbar-nav">
				<%= link_to fa_icon("plus") + " Create Question", new_question_path, class: "navbar-brand" %>
				<%= link_to fa_icon("plus") + " Create Contest", new_contest_path, class: "navbar-brand" %>
			</div>
			<div class="nav navbar-nav">
				<%= link_to fa_icon("file-text-o")+" Question List", questions_path, class: "navbar-brand" %>
				<%= link_to fa_icon("file-text-o")+" Contest List", contests_path, class: "navbar-brand" %>
			</div>
			<div id="clock" class="nav navbar-nav"></div><%# 時計 %>
			<li class="dropdown nav navbar-nav pull-right">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<%= image_tag user_icon(current_user) , size: "47x47", class: "img-circle"%> 
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to fa_icon("address-card") + " Profile", current_user %></li>
					<li class="divider"></li>
					<li><%= link_to fa_icon("user") + " Follower #{current_user.followers.length}", follower_list_user_path(current_user) %></li>
					<li class="divider"></li>
					<li><%= link_to fa_icon("user-o") + " Following #{current_user.following.length}", following_list_user_path(current_user) %></li>
					<li class="divider"></li>
					<li><%= link_to fa_icon("sign-out") + " Log out", destroy_user_session_path, method: :delete %></li>
				</ul>
			</li> 
			<div class="nav navbar-nav navbar-form">
				<%= form_tag user_search_result_path, method: 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
				<div class="form-group">
					<%= text_field_tag :search, params[:search], placeholder: "User name", class: "form-control", style: 'width: 80pt;' %>
				</div>
				<div class="form-group">
				<%= submit_tag "Search", name: nil, class: "btn btn-warning" %>
				</div>
				<% end %>
			</div>
		</div>
		<% else %>
		<div class="collapse navbar-collapse" id="top-nav">
			<div class="nav navbar-nav navbar-right">
				<%= link_to "Sign in", new_user_session_path, class: 'navbar-brand' %>
			</div>
		</div>
		<% end %>
	</div>
</nav>

<script>
	jQuery(
		function($){
			<% if @path.is('contests#show') || @path.is('questions#contest_show') || @path.is('judge_systems#contest_submit') %>
			<% if @contest.users.include?(current_user) && Time.now >= @contest.start_time && Time.now < @contest.finish_time %>
			$('#clock').flipcountdown({
				size:'md',
				beforeDateTime: '<%= @contest.finish_time.strftime('%m/%d/%Y %H:%M:%S') %>'
			});
			<% else %>
			$('#clock').flipcountdown();
			<% end %>
			<% else %>
			$('#clock').flipcountdown();
			<% end %>
		});
	</script>

app/views/layouts/_modal.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="start_pop" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><%= @contest.title %> START!!</h4>
			</div>
			<div class="modal-body">
			コンテスト: <%= @contest.title %> の開始時間です
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal" id="start_button">閉じる</button>
			</div>
		</div>
	</div>
</div>


<div class="modal fade" id="end_pop" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><%= @contest.title %> END!!</h4>
			</div>
			<div class="modal-body">
				コンテスト: <%= @contest.title %> の終了時間です
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal" id="end_button">閉じる</button>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_mordal_script.html.erb
	<% if (@path.is('contests#show') || @path.is('questions#contest_show')) && @contest.finish_time > Time.now %>
	<%= render 'layouts/modal' %>
	<script>
		jQuery(function($){
			setInterval(function(){
				var now_hour = new Date().getTime();
				if ( now_hour - <%= @contest.start_time.to_i * 1000 %> <= 1000 && now_hour - <%= @contest.start_time.to_i * 1000 %> >= 0 ){
					$('#start_pop').modal();
					$('#start_button').click(function(){
						location.reload();
					});
				} else if ( now_hour - <%= @contest.finish_time.to_i * 1000 %> <= 1000 && now_hour - <%= @contest.finish_time.to_i * 1000 %> >= 0 ) {
					$('#end_pop').modal();
					$('#end_button').click(function(){
						location.reload();
					});
				}
			},1000);
		});
	</script>
	<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Daisuki Club Online Judge</title>
	<script type="text/x-mathjax-config">
		MathJax.Hub.Config({
		tex2jax: {
		inlineMath: [ ['$','$'] ],
		processEscapes: true
	}
});
</script>
<meta name="turbolinks-cache-control" content="no-cache">
<%= mathjax_tag %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name= "viewport" content="width=device-width, initial-scale=1.0">
<%= render 'layouts/shim' %>
</head>
<body>

	<%= render 'layouts/header' %>
	<%= render 'layouts/mordal_script' %>

	<div class="wrapper">
		<div id="alert">
			<%= render 'layouts/alert' %>
		</div>
<div class="main_yield">
	<%= yield %>
</div>
		<div class="push"></div>
	</div>
	<div class="footer">
		<%= render 'layouts/footer' %>
	</div>	
</body>
</html>